- name: Install software
  hosts: localhost
  become: true
  tasks:
    - name: Install Java
      yum:
        name: java-11-openjdk
        state: present

    - name: Install wget
      yum:
        name: wget
        state: present

    - name: Install Elastic repo
      yum_repository:
        name: elastic-8.x
        description: Elastic repository for 8.x packages
        baseurl: https://artifacts.elastic.co/packages/8.x/yum
        gpgcheck: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: no

    - name: Install Logstash
      command:
        cmd: yum install --enablerepo=elastic-8.x logstash -y
        warn: no

    - name: Install MariaDB
      yum:
        name: mariadb-server
        state: present

    - name: Install Elastic Agent
      shell:
        cmd: |
          curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.3.0-linux-x86_64.tar.gz
          tar xzvf elastic-agent-8.3.0-linux-x86_64.tar.gz
          cd elastic-agent-8.3.0-linux-x86_64
          ./elastic-agent install -n
        warn: false
        ignore_errors: true


    - name: Download Kafka
      get_url:
        url: "http://apache.mirrors.hoobly.com/kafka/2.8.0/kafka_2.13-2.8.0.tgz"
        dest: "/opt/kafka_2.13-2.8.0.tgz"
        mode: '0755'

    - name: Extract Kafka
      unarchive:
        src: "/opt/kafka_2.13-2.8.0.tgz"
        dest: "/opt"
        remote_src: true

    - name: Setup single node Kafka with Kraft
      shell:
        cmd: |
          cd /opt/kafka_2.13-2.8.0
          bin/kafka-storage.sh random-uuid
          bin/kafka-server-start.sh config/kraft/server.properties &
          sleep 10
        creates: /opt/kafka_2.13-2.8.0/config/kraft/server.properties

    - name: Create Kafka topic
      command: "/opt/kafka_2.13-2.8.0/bin/kafka-topics.sh --create --topic quickstart-events --bootstrap-server localhost:9092"
      ignore_errors: yes # Ignore errors if topic already exists