- name: Install software
  hosts: localhost
  become: true
  tasks:
    - name: Install Java
      yum:
        name: java-11-openjdk
        state: present

    - name: Install wget
      yum:
        name: wget
        state: present

    - name: Install Elastic repo
      yum_repository:
        name: elastic-8.x
        description: Elastic repository for 8.x packages
        baseurl: https://artifacts.elastic.co/packages/8.x/yum
        gpgcheck: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: no

    - name: Install Logstash
      command:
        cmd: yum install --enablerepo=elastic-8.x logstash -y
        warn: no

    - name: Install MariaDB
      yum:
        name: mariadb-server
        state: present

    - name: Install Elastic Agent
      shell:
        cmd: |
          curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.3.0-linux-x86_64.tar.gz
          tar xzvf elastic-agent-8.3.0-linux-x86_64.tar.gz
          cd elastic-agent-8.3.0-linux-x86_64
          ./elastic-agent install -n
      ignore_errors: true

    - name: Download Kafka binary
      get_url:
        url: https://downloads.apache.org/kafka/3.5.0/kafka_2.13-3.5.0.tgz
        dest: /opt/kafka_2.13-3.5.0.tgz

    - name: Extract Kafka binary
      unarchive:
        src: /opt/kafka_2.13-3.5.0.tgz
        dest: /opt/
        remote_src: true


    - name: Start Kafka
      shell:
        cmd: |
          KAFKA_CLUSTER_ID="$(/opt/kafka_2.13-3.5.0/bin/kafka-storage.sh random-uuid)"
          /opt/kafka_2.13-3.5.0/bin/kafka-storage.sh format -t $KAFKA_CLUSTER_ID -c /opt/kafka_2.13-3.5.0/config/kraft/server.properties --ignore-formatted
          /opt/kafka_2.13-3.5.0/bin/kafka-server-start.sh config/kraft/server.properties


    - name: Wait for Kafka to start
      wait_for:
        host: localhost
        port: 9092
        delay: 10
        timeout: 300

    - name: Create Kafka topic
      command:
        cmd: /opt/kafka_2.13-3.5.0/bin/kafka-topics.sh --create --topic quickstart-events --bootstrap-server localhost:9092
      ignore_errors: true
